name: Unit test execution

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Build:
    permissions:
      id-token: write
      contents: read
      checks: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test with Coverage
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test run results
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ github.token }}
          min-coverage-overall: 80
          title: Code Coverage